# Get all products
GET http://localhost:4001/api/v1/products
content-type: application/json

###

# Get all products filter by category
GET http://localhost:4001/api/v1/products?category=generic
content-type: application/json

###

# Get one products by id
GET http://localhost:4001/api/v1/products/1
content-type: application/json
