# Purchase
POST http://localhost:4001/api/v1/transactions/cash
content-type: application/json

{
  "inventoryId": "1",
  "quantity": 1,
  "currencies": [
    {
      "value": 10,
      "quantity": 2
    },
    {
      "value": 5,
      "quantity": 1
    }
  ]
}
